Add type to make getPath call types
kingjan1999/platform-folders pull request #11
Opened 2019-05-23 16:28 UTC by moshfeu

2019-05-24 10:41 UTC, kingjan1999 requested changes
Thank you very much! Just two minor comments

2019-05-24 10:41 UTC, kingjan1999 commented on src/index.ts
> +type Folder = 'home' | 'appData' | 'appdata' | 'userData' | 'desktop' | 'documents' | 'downloads' | 'music' | 'pictures' | 'videos' | 'cache' | 'savegames';
Can you insert one or more line break(s) here? The line is quite long.

2019-05-24 10:41 UTC, kingjan1999 commented on src/index.ts
>  export default function getPath(name: string): string|undefined {
I think you have to replace `name: string` with `name: Folder` to use the type declared above

2019-05-25 18:27 UTC, moshfeu commented
Done. Thanks :)

2019-05-25 18:31 UTC, kingjan1999 approved these changes

2019-05-25 18:31 UTC, merged

2019-05-25 18:32 UTC, kingjan1999 commented
Thank you, merged!